# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gem-github}
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Dollar"]
  s.date = %q{2009-08-19}
  s.description = %q{
Get Github statistics for various versions of a gem

$ gem github railroad

peterhoeg-railroad             fork:no   watchers:7   updated:2009-05-16
factorylabs-railroad           fork:yes  watchers:8   updated:2009-01-05
bryanlarsen-railroad           fork:yes  watchers:7   updated:2009-06-30
nono-railroad                  fork:yes  watchers:7   updated:2009-03-13
ddollar-railroad               fork:yes  watchers:2   updated:2009-03-13
terotil-railroad               fork:yes  watchers:2   updated:2009-02-13

}
  s.email = %q{<ddollar@gmail.com>}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "gem-github.gemspec",
     "lib/gem/commands/github_command.rb",
     "lib/rubygems_plugin.rb",
     "test/gem-github-stats_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/ddollar/gem-github-stats}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Show Github-related stats of the same gem from different users}
  s.test_files = [
    "test/gem-github-stats_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fcoury-octopi>, [">= 0.1.0"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<fcoury-octopi>, [">= 0.1.0"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<fcoury-octopi>, [">= 0.1.0"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end
